version: "3.8"

volumes:
  yamdb_deploy_postgres_data:
  static_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - yamdb_deploy_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DB_HOST
      - DB_PORT

  web:
    image: sh2man/yamdb:latest
    restart: always
    depends_on:
      - db
    volumes:
      - yamdb_deploy_static_data:/app/static/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DB_HOST
      - DB_PORT

  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - yamdb_deploy_static_data:/app/static/:ro
